"""status.py — GENERATE STATUS.md from status: fields and counts. Never hand-edited (spec §5a).

  python tools/status.py            write STATUS.md and print it

Per production: brief/development status (front-matter `status:`), characters and locations
with their status, approved refs vs candidates in refs/manifest.json, per unit: beats,
prompt lines, jobs by status, renders landed, cuts on the drive, postmortem status, and
the next gate that is not yet satisfied.
"""
from __future__ import annotations

import csv
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import paths  # noqa: E402
import skeleton  # noqa: E402

FM = re.compile(r"(?s)\A---\n(.*?)\n---")


def fm_status(p: Path) -> str:
    if not p.is_file():
        return "missing"
    m = FM.match(p.read_text(encoding="utf-8"))
    if not m:
        return "no front-matter"
    for line in m.group(1).splitlines():
        if line.startswith("status:"):
            return line.split(":", 1)[1].strip() or "blank"
    return "no status"


def jsonl(p: Path) -> list[dict]:
    if not p.is_file():
        return []
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]


def production_block(prod: Path) -> list[str]:
    ident = skeleton.load_identity(prod)
    out = [f"## {prod.name} — {ident.TITLE or '(untitled)'} ({ident.FORMAT or '?'})", ""]
    out.append(f"- development: **{fm_status(prod / 'development.md')}** · brief: **{fm_status(prod / 'brief.md')}**")
    chars = [(p.stem, fm_status(p)) for p in sorted((prod / "characters").glob("*.md")) if p.name != "_TEMPLATE.md"]
    locs = [(p.stem, fm_status(p)) for p in sorted((prod / "locations").glob("*.md")) if p.name != "_TEMPLATE.md"]
    out.append(f"- canon: {len(chars)} character(s) " + (", ".join(f"{n}={s}" for n, s in chars) if chars else "—")
               + f"; {len(locs)} location(s) " + (", ".join(f"{n}={s}" for n, s in locs) if locs else "—"))
    man = json.loads((prod / "refs" / "manifest.json").read_text(encoding="utf-8")) if (prod / "refs" / "manifest.json").is_file() else {"refs": []}
    approved = [r for r in man.get("refs", []) if r.get("status") == "approved"]
    out.append(f"- refs: {len(approved)} approved / {len(man.get('refs', []))} in manifest; identity declares {len(ident.CAST)} cast + {len(ident.LOCATIONS)} location slot(s)")
    renders = jsonl(prod / "renders.jsonl")
    gate = None
    for unit in skeleton.units(prod, ident.FORMAT or "film"):
        uname = "(film)" if unit == prod else unit.name
        beats = []
        if (unit / "beats.csv").is_file():
            with (unit / "beats.csv").open(encoding="utf-8", newline="") as f:
                beats = [r for r in csv.DictReader(f) if r.get("beat", "").strip()]
        frames = sum(int(b["frames"]) for b in beats if b.get("frames", "").strip().isdigit())
        lines = {p.name: len([l for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]) for p in (unit / "prompts").glob("*.lines")} if (unit / "prompts").is_dir() else {}
        jobs = jsonl(unit / "jobs.jsonl")
        by = {}
        for j in jobs:
            by[j.get("status") or "new"] = by.get(j.get("status") or "new", 0) + 1
        cuts = sorted(p.name for p in (paths.media_for(prod.name, *([] if unit == prod else [unit.name]), "cuts")).glob("*.json")) if paths.MEDIA.is_dir() else []
        out.append(f"- {uname}: {len(beats)} beat(s) = {frames} f ({frames / 24:.1f} s) · prompts {lines or '—'} · jobs {by or '—'} · "
                   f"renders landed {sum(1 for r in renders if r.get('status') == 'landed' and r.get('unit') == (None if unit == prod else unit.name))} · "
                   f"cuts {cuts or '—'} · postmortem **{fm_status(unit / 'postmortem.md')}**")
        if gate is None:
            if fm_status(prod / "development.md") != "approved": gate = "G0 development"
            elif fm_status(prod / "brief.md") != "approved": gate = "G1 brief"
            elif not chars or any(s != "approved" for _, s in chars): gate = "G2 canon"
            elif not beats: gate = "G3 beats"
            elif not approved: gate = "G4 refs"
            elif not lines: gate = "preflight prompts"
            elif not any(r.get("proof") for r in jobs): gate = "G5 proof"
            elif by.get("landed", 0) < len(beats): gate = "board"
            elif not cuts: gate = "cut"
            elif fm_status(unit / "postmortem.md") != "approved": gate = "G6 postmortem"
    out.append(f"- **next gate: {gate or 'none — done'}**")
    out.append("")
    return out


def main() -> int:
    lines = ["# STATUS", "", f"Generated by `tools/status.py` {datetime.now(timezone.utc).isoformat(timespec='minutes')} — do not edit.", "",
             f"Template version {skeleton.template_version()} · graphs in routing.md · findings: see `tools/findings.py`", ""]
    prods = skeleton.productions()
    if not prods:
        lines.append("_No productions yet. `python tools/new_production.py <slug> --format film|show --title T`_")
    for p in prods:
        lines += production_block(p)
    text = "\n".join(lines) + "\n"
    (paths.REPO / "STATUS.md").write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
